[package]
name = "plicer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
dirs = "4.0.0"
image = "0.24.5"
rand = "0.8.5"
toml = "0.7.2"
walkdir = "2.3.2"
